version: '3.0'
services:
  magento-test:
    image: emarsys/ems-integration-magento-sampledata:2.3.3ce
    ports:
      - "8889:80"
    links:
      - db
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=magento_test
      - MAGENTO_URL=http://magento-test.local
    volumes:
      - ./..:/app/vendor/emartech/emarsys-magento2-extension
      - ./setup:/opt/emartech/setup
      - ./php.ini:/opt/docker/etc/php/php.ini
      - ./cache-flush.php:/app/cache-flush.php
      - ./Magento/customer-data.js:/app/vendor/magento/module-customer/view/frontend/web/js/customer-data.js
      # - ./dev/Docker/website2.conf:/opt/docker/etc/httpd/vhost.common.d/website2.conf
    command: ["/opt/emartech/wait-for-it.sh", "db:3306", "--timeout=30", "--strict", "--", "/opt/emartech/init"]
  magento-dev:
    image: emarsys/ems-integration-magento-sampledata:2.3.3ce
    ports:
      - "8888:80"
    links:
      - db
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=magento_dev
      - MAGENTO_URL=http://magento-dev.local:8888
    volumes:
      - ./..:/app/vendor/emartech/emarsys-magento2-extension
      - ./setup:/opt/emartech/setup
      - ./php.ini:/opt/docker/etc/php/php.ini
      # - ./Docker/website2.conf:/opt/docker/etc/httpd/conf.d/website2.conf
    command: ["/opt/emartech/wait-for-it.sh", "db:3306", "--timeout=30", "--strict", "--", "/opt/emartech/init"]
  db:
    image: healthcheck/percona
    restart: always
    # volumes:
    #   - magento-db:/var/lib/mysql
    ports:
      - "13306:3306"
    env_file:
      - .env
  node:
    container_name: mage_node
    build:
      context: .
      dockerfile: ./Docker/Dockerfile-node
      args:
        - NPM_TOKEN=$NPM_TOKEN
    volumes:
      - ./test:/test
    ipc: host
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=magento_test
      - MAGENTO_URL=magento-test.local
      - CYPRESS_PROJECT_ID=xo2cjm
    links:
      - magento-test:magento-test.local
      - db
# volumes:
#   magento-db:
