version: "3.2"

services:
  db:
    image: healthcheck/percona
    restart: always
    env_file:
      - .env
  magento-test:
    image: emarsys/ems-integration-magento-sampledata:$VERSION
    volumes:
      - ../..:/app/vendor/emartech/emarsys-magento2-extension
      - ../setup:/opt/emartech/setup
      - ../php.ini:/opt/docker/etc/php/php.ini
      - ../cache-flush.php:/app/cache-flush.php
      - ../Magento/customer-data.js:/app/vendor/magento/module-customer/view/frontend/web/js/customer-data.js
    environment:
      - MAGENTO_URL=http://magento-test.local
    env_file:
      - .env
    command: ["/opt/emartech/wait-for-it.sh", "db:3306", "--timeout=30", "--strict", "--", "/opt/emartech/init"]
    links:
      - db
  node:
    image: mage_node
    ipc: host
    env_file:
      - .env
    environment:
      - NPM_TOKEN=$NPM_TOKEN
      - MYSQL_DATABASE=magento
      - MAGENTO_URL=magento-test.local
      - TABLE_PREFIX=$TABLE_PREFIX
    links:
      - magento-test:magento-test.local
      - db